export const interstellarMock = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
      genre_ids: [12, 18, 878],
      id: 157336,
      original_language: "en",
      original_title: "Interstellar",
      overview:
        "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
      popularity: 172.272,
      poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      release_date: "2014-11-05",
      title: "Interstellar",
      video: false,
      vote_average: 8.409,
      vote_count: 32000,
    },
    {
      adult: false,
      backdrop_path: "/8C32MMrMYT5gON7nXgEGeM4puH4.jpg",
      genre_ids: [99],
      id: 336592,
      original_language: "en",
      original_title: "The Science of Interstellar",
      overview:
        "Matthew McConaughey narrates a fascinating look at Christopher Nolan's sci-fi film Interstellar, including scientific foundations, the work of consulting Scientist Kip Thorne, basic film themes, the science behind the search for planets capable of hosting life, space-time and the theory of relativity, the science of wormholes and black holes, crafting the film's visuals based on real scientific observation, the birth of the universe, the Dust Bowl and the evolution of dust as a toxin, the likelihood of future dust storms, the prospects of escaping a dying or doomed planet, and the possibilities of colonizing Mars.",
      popularity: 17.273,
      poster_path: "/qUZiVjFBd67WKktIrjJ9H3tesyo.jpg",
      release_date: "2014-11-25",
      title: "The Science of Interstellar",
      video: false,
      vote_average: 6.8,
      vote_count: 24,
    },
    {
      adult: false,
      backdrop_path: "/fTcs5ejlN1MwwLSSv9aU1mi5alL.jpg",
      genre_ids: [99],
      id: 301959,
      original_language: "en",
      original_title: "Interstellar: Nolan's Odyssey",
      overview: "A look behind the lens of Christopher Nolan's space epic.",
      popularity: 15.143,
      poster_path: "/i4PpBcuLvdcJwIf3hkcV9QDR1iH.jpg",
      release_date: "2014-11-05",
      title: "Interstellar: Nolan's Odyssey",
      video: false,
      vote_average: 7.699,
      vote_count: 166,
    },
    {
      adult: false,
      backdrop_path: "/lQS9il7YqGjmmBefZY27uG5wbzT.jpg",
      genre_ids: [99],
      id: 660698,
      original_language: "en",
      original_title: "Faster Than Light: the Dream of Interstellar Flight",
      overview:
        "“Faster Than Light” explores the longstanding quest to develop spacecraft with enough power and speed to reach the stars. The film asks: What will it take to reach a newly discovered planet circling our Sun’s nearest neighbor, Proxima Centauri? Based on real science and engineering, “Faster Than Light” takes audiences on a thrilling journey into the future, aboard laser-driven space sails, antimatter engines, and even warp drive – right out of science fiction. “Who can say how far, and how fast, our technology will one day take us?” said director Thomas Lucas.",
      popularity: 6.911,
      poster_path: "/mbgJxB70uMFK2H8DXHUj5lAMgXx.jpg",
      release_date: "2017-06-07",
      title: "Faster Than Light: the Dream of Interstellar Flight",
      video: false,
      vote_average: 6.0,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 529107,
      original_language: "en",
      original_title: "Inside 'Interstellar'",
      overview:
        "Cast and crew of Christopher Nolan's \"Interstellar\" discuss project origins, the film's imagery, ambitions, incorporating IMAX footage, the human element within the film, arm shooting locations outside of Calgary, the set construction and design, working with real corn, mechanical characters, including backstory, design, the blend of practical and digital effects in bringing them to life, the differences in the characters, the human performances behind the characters, the creative process behind the film's music, Icelandic locations, vehicle interiors, the processes of simulating the absence of gravity, the crucial end-film visuals and influence and inspiration for future generations",
      popularity: 7.569,
      poster_path: "/vemBplPKQhVe5cRWL7kxtgp15Vq.jpg",
      release_date: "2015-03-31",
      title: "Inside 'Interstellar'",
      video: false,
      vote_average: 7.0,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 287954,
      original_language: "en",
      original_title: "Lolita from Interstellar Space",
      overview:
        "An undeniably beautiful alien is sent to Earth to study the complex mating rituals of human beings, which leads to the young interstellar traveler experiencing the passion that surrounds the centuries-old ritual of the species.",
      popularity: 7.159,
      poster_path: "/nhWlip1s5YzhRFKGlHABGJrBhZn.jpg",
      release_date: "2014-03-08",
      title: "Lolita from Interstellar Space",
      video: false,
      vote_average: 5.4,
      vote_count: 10,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28],
      id: 649745,
      original_language: "zh",
      original_title: "星际流浪",
      overview:
        'The film tells that the catastrophe era, the earth is a waste land, the survivors are divided into wanderers and civilians, they are attached to the rule of the interstellar armed groups, in which the rogues rely on the plundering of civilian materials as a livelihood, making civilians in this harsh It is difficult to survive in the environment. After a hundred years of black technology explosion, it will bring about a civilized renaissance. In the face of the deteriorating planet, mankind is determined to continue the race and is determined to interstellar immigration. The "curvature engine" developed by the Chinese researcher Hailei has become the key to the interstellar immigration, and is also the target of robbers and interstellar armed groups.',
      popularity: 1.44,
      poster_path: "/oUWDbde5bWu9syBZglWDIwB1SPm.jpg",
      release_date: "2019-08-02",
      title: "Interstellar Wandering",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/wUZID3WzrzuIQmcIjXahZkV1ItI.jpg",
      genre_ids: [878],
      id: 398188,
      original_language: "en",
      original_title: "Interstellar Wars",
      overview:
        "For millennia the Alien force has watched and waited, a brooding menace that has now at last decided to take over the Earth. Communications systems worldwide are sent into chaos by a strange atmospheric interference, a massive spaceship heads towards Earth and smaller spaceships begin to cover entire cities. Suddenly, the wonder turns into horror as the spaceships destroy the cities with energy weapons. When the world counterattacks, the alien ships are invincible to military weapons.  The survivors have to use their wits to kill the aliens, or die.",
      popularity: 6.393,
      poster_path: "/4uWZ8cdrXMLiyLNgdmqQCIM6z40.jpg",
      release_date: "2016-06-09",
      title: "Interstellar Wars",
      video: false,
      vote_average: 3.292,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 14, 878],
      id: 460616,
      original_language: "en",
      original_title: "Interstellar Civil War: Shadows of the Empire",
      overview:
        "The Imperial Empire is attacked by an Alliance of rebels led by fanatical mystics. The ruler, Empress Nobu, the 8th generation of her family, wants to execute a bold plan to rescue a cyborg, Leah C6, trapped on the battle ravaged planet Endor. The Empress believes Leah C6 holds the secret to destroying the Alliance of Rebels before their insurgency can kill millions of citizens of the Empire. She recruits her heroic fleet commander, Lord General Luka Raan and asks him to gather a team from the Empire's elite soldiers, the Galactic Rangers. Raan assembles the team in the ruins of Endor which was attacked by depraved Rebels and outlaws led by, Kindo-Ker, a fanatical mystic in Dark Energy. The Galactic Rangers begin a desperate search to find and rescue Leah C6 before the Alliance Rebels can.",
      popularity: 1.074,
      poster_path: "/1lDY7ZpEKOl3OaIQURjRbmFPfT8.jpg",
      release_date: "2018-04-15",
      title: "Interstellar Civil War: Shadows of the Empire",
      video: false,
      vote_average: 4.0,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 838389,
      original_language: "en",
      original_title: "Interstellar: Desgornia's Cut",
      overview:
        "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      popularity: 1.956,
      poster_path: "/geOB25wA6VHSlANpJ1UMyuokjJl.jpg",
      release_date: "",
      title: "Interstellar: Desgornia's Cut",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 18],
      id: 716603,
      original_language: "en",
      original_title: "Only Interstellar Pinball Lives Forever",
      overview:
        "A young boy (played by an actual re-purposed Sunday school puppet) loses all faith in religion and afterlife options after having to bury his umpteenth pet, and vows that someday, when he's an adult with money, he'll find a way to become an 'eternal molecule' through science. Then, twenty-two years later, the playing of a pinball game brings dredges up the memory of that vow. Utilizing the hallucinogenic properties of alcohol and cough syrup blends, he undertakes the design of a pinball machine so poignant and dignified that it will convince scientists to create a pinball that we can download our consciousness into and thereby become digitally immortal.",
      popularity: 0.656,
      poster_path: "/uLJMGZlrkmvAO9Ria9zrp8GUqjx.jpg",
      release_date: "2010-06-28",
      title: "Only Interstellar Pinball Lives Forever",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 986255,
      original_language: "en",
      original_title: "How to Colonize the Stars: The Challenge of Interstellar Flight",
      overview:
        "Leading physicists and engineers in the field of interstellar travel discuss some of the deep issues we face when considering the problem of sending spacecraft to other stars. Will mankind ever truly become a space fairing civilization? Space colonization is no longer the fodder of science fiction, it is becoming a reality. We'll need to learn how to grow food, manufacture and live off our planet.",
      popularity: 0.6,
      poster_path: "/ddYoMPJioxY7qQxt7JyUaLCWMjw.jpg",
      release_date: "2009-06-09",
      title: "How to Colonize the Stars: The Challenge of Interstellar Flight",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 763179,
      original_language: "en",
      original_title: "Cosmic Journey: The Voyager Interstellar Mission and Message",
      overview:
        'The farthest Voyager: "Cosmic Journey," a documentary premiering on the A\u0026E cable network, tells the saga of the farthest-flung space journey to date - the Voyager interstellar mission, which started out 25 years ago and sailed past Jupiter, Saturn, Uranus and Neptune in the 1980s.',
      popularity: 0.6,
      poster_path: null,
      release_date: "2003-01-16",
      title: "Cosmic Journey: The Voyager Interstellar Mission and Message",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [12],
      id: 552531,
      original_language: "en",
      original_title: "The Prom Goer's Interstellar Excursion",
      overview:
        "High schooler Bennett lands the prom date of his dreams, Sophie, just days before the dance. Not long after, he witnesses Sophie being abducted by aliens in the middle of the New Mexico desert.",
      popularity: 0.6,
      poster_path: null,
      release_date: "",
      title: "The Prom Goer's Interstellar Excursion",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/ynF37QsffZ1b3Xm2ktpb79ioP6R.jpg",
      genre_ids: [99],
      id: 436305,
      original_language: "en",
      original_title: "The Farthest",
      overview:
        "The captivating tales of the people and events behind one of humanity's greatest achievements in exploration: NASA's Voyager mission.",
      popularity: 3.446,
      poster_path: "/jHbSJo4FoKvqaGn3b7q49bcSYVZ.jpg",
      release_date: "2018-03-15",
      title: "The Farthest",
      video: false,
      vote_average: 7.656,
      vote_count: 45,
    },
    {
      adult: false,
      backdrop_path: "/yl9QqtS3tbLCL4e6lHM349joALK.jpg",
      genre_ids: [28, 53, 878],
      id: 47663,
      original_language: "en",
      original_title: "Trancers 5: Sudden Deth",
      overview:
        "Jack Deth is back for one more round with the trancers. Jack must attempt to find his way home from the other-dimensional world of Orpheus, where magic works and the trancers were the ruling class (before Trancers IV, that is). Unfortunately, Jack's quest to find the mystical Tiamond in the Castle of Unrelenting Terror may be thwarted by the return of Caliban, king of the trancers who was thought dead.",
      popularity: 2.83,
      poster_path: "/t4to2HtWP1lT6TkvTwSUD7cQqIH.jpg",
      release_date: "1994-09-10",
      title: "Trancers 5: Sudden Deth",
      video: false,
      vote_average: 4.6,
      vote_count: 21,
    },
    {
      adult: false,
      backdrop_path: "/aPXNyG6035Wz2DhtGAgf7PeGNsz.jpg",
      genre_ids: [878, 28],
      id: 47662,
      original_language: "en",
      original_title: "Trancers 4: Jack of Swords",
      overview:
        'Jack is now back in the future. He had since lost Lena, and finds out that he\'s lost his other wife Alice to none other than Harris. While heading out for another assignment, something goes awry with the TCL chamber. Jack finds himself in a whole new dimension. He also runs across a different version of trancers. These guys seem to be in control of this planet. Jack manages to assist a rebel group known as the "Tunnel Rats" crush the rule of the evil Lord Calaban.',
      popularity: 4.929,
      poster_path: "/ec081IWKkRalPO14KAmqJ2vWeYB.jpg",
      release_date: "1994-02-02",
      title: "Trancers 4: Jack of Swords",
      video: false,
      vote_average: 5.1,
      vote_count: 25,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [878],
      id: 261443,
      original_language: "en",
      original_title: "Angry Planet",
      overview:
        "A criminal sentenced to life on a prison planet reveals his true purpose: to extract revenge on the killers who murdered his family.",
      popularity: 1.4,
      poster_path: "/6Bv0rl9R5gaN8X58LOjUT4MWKR7.jpg",
      release_date: "2008-01-01",
      title: "Angry Planet",
      video: false,
      vote_average: 2.8,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 772265,
      original_language: "zh",
      original_title: "星际变种",
      overview:
        'After long years of searching, the unknown creature was finally captured by the crew of the Thunder and named "Baal". Under the lure of Baal, the young Jamie released it. "Baal" who escaped from the experimental tank killed all the crew and Jamie\'s parents, and the young Jamie escaped back to Earth in an escape capsule alone. Twenty years later, a variant of "Baal" appeared on the earth, and Jamie began the story of the journey to save mankind and self-redemption',
      popularity: 3.32,
      poster_path: "/mMidfcVVaESbYdF9Tzgejp3FvPR.jpg",
      release_date: "2023-08-22",
      title: "Variant",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/l94Zv2Yn2BYgfAw19gJRaiJ1PGh.jpg",
      genre_ids: [28],
      id: 1042070,
      original_language: "zh",
      original_title: "百慕大星际流浪者",
      overview:
        "In the year 2055 AD (333 years of the planet Bermuda), an international research flying saucer led by Chinese captain Mo Jiahai was searching for planets with signs of life in space. They found a humanoid planet but ran out of energy while performing space shuttle and could no longer start up just after reaching this planet. The surviving Earthlings found that their bodies' respiratory systems could not fully adapt. Unwilling to pin their hopes entirely on the AI robots, some of the Earthlings endured the uncomfortable air and stepped out of the ship, where they secretly reproduced on the planet. Hundreds of years passed, and the Earthlings who gradually adapted to the planet Bermuda also reproduced secretly from generation to generation, with the secret of the flying saucer buried deep in the desert of the planet.",
      popularity: 0.969,
      poster_path: "/mvT8itefntNmKb69IJFA9SjWrdH.jpg",
      release_date: "2022-10-27",
      title: "The Bermuda Star Rangers",
      video: false,
      vote_average: 3.5,
      vote_count: 2,
    },
  ],
  total_pages: 1,
  total_results: 20,
};

export const martianMock = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/3dPhs7hUnQLphDFzdkD407VZDYo.jpg",
      genre_ids: [18, 12, 878],
      id: 286217,
      original_language: "en",
      original_title: "The Martian",
      overview:
        "During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive.",
      popularity: 51.526,
      poster_path: "/5BHuvQ6p9kfc091Z8RiFNhCwL4b.jpg",
      release_date: "2015-09-30",
      title: "The Martian",
      video: false,
      vote_average: 7.676,
      vote_count: 18331,
    },
    {
      adult: false,
      backdrop_path: "/jRtMuANI62nS0oOEcKyewhizFFr.jpg",
      genre_ids: [35, 14, 878],
      id: 32307,
      original_language: "en",
      original_title: "Santa Claus Conquers the Martians",
      overview:
        "Martians fear their children have become lazy and joyless due to their newfound obsession with Earth TV shows. After ancient Martian leader Chochem suggests that the children of Mars need more fun—including their own Santa Claus—supreme leader Lord Kimar assembles an expedition to Earth. Once there, they kidnap two children who lead them to the North Pole, then capture the real Santa Claus, taking all three back to Mars in an attempt to bring the Martian children happiness.",
      popularity: 4.177,
      poster_path: "/f8lxrcMx98AuvlLSb2hPkz0CuH0.jpg",
      release_date: "1964-11-14",
      title: "Santa Claus Conquers the Martians",
      video: false,
      vote_average: 3.1,
      vote_count: 108,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16],
      id: 819446,
      original_language: "is",
      original_title: "The Last Two Martians on Mars",
      overview:
        "A short fast paced cut-out animation. It tells the story of Diane and Bob, the last two surviving Martians on Mars.",
      popularity: 0.6,
      poster_path: null,
      release_date: "1997-01-01",
      title: "The Last Two Martians on Mars",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/zA9p0cZK0AcWepTslez1GL3AwH1.jpg",
      genre_ids: [16, 878, 18, 28],
      id: 36613,
      original_language: "ja",
      original_title: "機動戦艦ナデシコ -The prince of darkness-",
      overview:
        "Two years have passed since the Great War. Akito and Yurika have vanished. The Jovians and the Earthlings have joined forces and Ruri is now captain of Nadesico B. As the popularity of Boson Jumping grows, a vast transportation network has been developed. Dubbed the Hisago Plan, this network of Chulip portals holds the answers to the mysteries behind Bose particles and their power. If those secrets should fall into the wrong hands, it could mean big trouble. And big trouble there is. A Martian splinter group has launched an offensive, leaving the United Forces befuddled and desperate. So much so, in fact, that the former crew of the Nadesico is called back to active duty for a special unsanctioned mission-to save us all. Does this menagerie of misfits have what it takes? Who will win the race for the Boson technology? And what the heck happened to Akito and Yurika?",
      popularity: 9.918,
      poster_path: "/j4OZZpKJh5Qb5peTZVwbtTaD0tY.jpg",
      release_date: "1998-08-01",
      title: "Martian Successor Nadesico: The Motion Picture - Prince of Darkness",
      video: false,
      vote_average: 6.8,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: "/uMenBxDcRzP395infqaFG8sPyqY.jpg",
      genre_ids: [28, 878, 14],
      id: 80766,
      original_language: "es",
      original_title: "Santo el enmascarado de plata vs. la invasión de los marcianos",
      overview:
        "In this Mexican sci-fi fantasy, big beefy Martians invade the earth. Ostensibly, they have come to warn people about the dangers of nuclear testing and exploring space, but their real mission becomes manifest when they begin using their special powers and gadgets to exploit weak earthlings.",
      popularity: 1.401,
      poster_path: "/qUjR8YUmnuFozJG2uru3v3nq9Tw.jpg",
      release_date: "1967-07-27",
      title: "Santo vs. the Martian Invasion",
      video: false,
      vote_average: 5.4,
      vote_count: 14,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 603459,
      original_language: "en",
      original_title: "The Long Way Home: Making 'The Martian'",
      overview:
        'A long form documentary on the making of Ridley Scott\'s film, "The Martian," featuring interviews with its cast and crew.',
      popularity: 1.4,
      poster_path: "/jo4bpujR5acfcJrLkH0TZ3MumjG.jpg",
      release_date: "2016-06-07",
      title: "The Long Way Home: Making 'The Martian'",
      video: false,
      vote_average: 6.0,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/rqVETNBEimEv0PJTvMVmpHw88MJ.jpg",
      genre_ids: [18, 10752, 36, 878, 99],
      id: 247845,
      original_language: "en",
      original_title: "The Great Martian War 1913–1917",
      overview:
        "Documentary-drama recounting the Martian War of 1913–1917. Europe was on tenterhooks in the 2nd decade of the 20th century, everyone was expecting a Great War between the major European powers. But then, in 1913, something crashed into the forests of SW Germany. Troops were sent to investigate but were wiped out. Martian fighting machines began making their way across Western Europe and the countries of Europe combined forces to resist them. With aspects taken from ‘The War of the Worlds’ by H.G. Wells and from WWI itself, this dramatisation presents a documentary style look at events as they unfolded and the effect they had of our world today. Lots of references to real events including the mass attacks and defeats as men were thrown against machines on the Western front, the Christmas truce and the Angel of Mons, America's isolationism and late entry into the conflict, the worldwide Spanish flu epidemic that killed more people than the war, and many other things.",
      popularity: 1.346,
      poster_path: "/4dGtDwLsT8Jq83PaNAurBC9sQCQ.jpg",
      release_date: "2013-12-08",
      title: "The Great Martian War 1913–1917",
      video: false,
      vote_average: 6.4,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: "/w1iXHAvFFDjfjrxnyXWjK1cgCdp.jpg",
      genre_ids: [16],
      id: 26470,
      original_language: "en",
      original_title: "Marvin The Martian: Space Tunes",
      overview:
        'Collection of classic cartoons including "Duck Dodgers in the 24 1/2 Century," "Hareway to the Stars," "The Hasty Hare," "Duck Dodgers and the Return of the 24 1/2 Century," "Mad as a Mars Hare," "Spaced Out Bunny," and "Haredevil Hare."',
      popularity: 0.901,
      poster_path: "/3cO8NxBWDhEUvXVdyAYfQLNCqFH.jpg",
      release_date: "1998-01-01",
      title: "Marvin The Martian: Space Tunes",
      video: true,
      vote_average: 7.0,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 335547,
      original_language: "ru",
      original_title: "Тайная эстетика марсианских шпионов",
      overview:
        "Martian Spies tells a love story between a boy who pretends to be a terrorist and a young girl, who is the wife of a KGB agent. The boy tells her that he has been hired to shoot the president – Yeltsin. The end is poetic yet addressing the politics of revenge and corruption in Russia. Miners stand in front of their mine, singing a song, which tells the story of contemporary Russian politics.",
      popularity: 0.6,
      poster_path: "/pmvdjK6Qcp61W3hOjJV7TgGuo7R.jpg",
      release_date: "1997-01-11",
      title: "The Secret Aesthetics of the Martian Spies",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/3nF5Agpp1xy5zKdxboD0fTXuenH.jpg",
      genre_ids: [16, 35, 878],
      id: 100512,
      original_language: "es",
      original_title: "Mercano, el Marciano",
      overview:
        "When his pet is killed by a probe from earth, Mercano, a Martian, travels to earth angered. Landing in Buenos Aires, at first noone takes any notice of him.",
      popularity: 1.731,
      poster_path: "/ta70hiwyF9NJX0CCqdsWWRg9vBL.jpg",
      release_date: "2002-10-03",
      title: "Mercano the Martian",
      video: false,
      vote_average: 5.6,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16],
      id: 1105300,
      original_language: "en",
      original_title: "Marvin the Martian in the Third Dimension",
      overview:
        "Marvin the Martian mistakes Daffy Duck's Duck Dodgers show, in which Dodgers announces that his forces are about to invade Mars, for a live broadcast and retaliates by going after Daffy, who still thinks they're shooting the show.",
      popularity: 0.6,
      poster_path: "/t3vbN5cxtV4lxtgE8bTcqQD6EPk.jpg",
      release_date: "1996-10-23",
      title: "Marvin the Martian in the Third Dimension",
      video: false,
      vote_average: 6.0,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 83011,
      original_language: "en",
      original_title: "Cinematic Titanic: Santa Claus Conquers the Martians",
      overview:
        "The children of Mars are in a funk, and nothing on the red planet seems to be able to cheer them up. Martian King Kimar comes up with the only reasonable solution: kidnap Santa Claus from Earth's North Pole and bring him to their planet to make toys for their joyless, listless little green kids. Meanwhile, two Earth children get wise to the plan and are abducted along with Santa to prevent them from talking to the authorities. Luckily for them, Dropo, the Jerry Lewis of the fourth planet from the sun, is there to help them. The fiendish plot doesn't go according to plan, and there's plenty of intrigue, double-crossing, mistaken identity and stock footage for kids of all ages and planets to enjoy.  Poorly conceived, sloppily made, and unfailingly bizarre, \"Santa Claus Conquers the Martians\" is the ultimate Christmas movie-riffing classic (as fans of MST3K know) which is why Cinematic Titanic chose to revisit, re-riff, and release this holiday hamfest with all new jokes. Merry Crap-mas!",
      popularity: 0.6,
      poster_path: "/jU3BbqvZFXFeisJpP7dK7A0GKdK.jpg",
      release_date: "2008-11-20",
      title: "Cinematic Titanic: Santa Claus Conquers the Martians",
      video: false,
      vote_average: 8.3,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/3SzmUjfKSMslKOSYoe4F8YdsmCC.jpg",
      genre_ids: [10751, 35, 878],
      id: 85605,
      original_language: "fr",
      original_title: "Le martien de Noël",
      overview:
        "A martian comes to a small town in Quebec and becomes friends with the town children. He gives them candy to get the children into his spacecraft. This alarms the parents but he wins them over and they have a great big Christmas party.",
      popularity: 0.6,
      poster_path: "/3hrXefUybywCUOJmdjpMvJjwTtJ.jpg",
      release_date: "1971-01-01",
      title: "The Christmas Martian",
      video: false,
      vote_average: 4.4,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/bgKL4E4oxdsOmvweSQNIlBCq3is.jpg",
      genre_ids: [99],
      id: 837912,
      original_language: "en",
      original_title: "The Martians Are Coming!: The Making of 'Invaders from Mars'",
      overview: "Documentary about the making of Invaders from Mars",
      popularity: 0.6,
      poster_path: "/bLcioUstupINUjRy9kVvcHfrhx9.jpg",
      release_date: "2015-04-07",
      title: "The Martians Are Coming!: The Making of 'Invaders from Mars'",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16],
      id: 778017,
      original_language: "en",
      original_title: "Marvin the Martian \u0026 K9: 50 Years on Earth",
      overview:
        'Collection of classic cartoons including "Haredevil Hare", "Mad as a Mars Hare", "Duck Dodgers and the Return of the 24 1/2th Century", "Spacedout Bunny", "Lumber Jack Rabbit", and "Hyde and Go Tweet".',
      popularity: 1.453,
      poster_path: "/g7FXPUZZ5MW4hTj4RQFbyFcI0RG.jpg",
      release_date: "1998-07-21",
      title: "Marvin the Martian \u0026 K9: 50 Years on Earth",
      video: true,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 691539,
      original_language: "en",
      original_title: "Rifftrax Live: Santa Claus Conquers the Martians",
      overview:
        "The nasty Martian villain Voldar (his face is coated in green oil and he has a huge mustache, therefore he’s evil) captures two Earth children, Billy and Betty, who don’t hold out for even a minute but rat out our fattest, jolliest elf without a struggle. Voldar takes Santa and the children prisoner and heads off for Mars. Only the bravery of Billy and Betty and the bumbling of a stowaway and “the laziest man on Mars”, Droppo, can foil Voldar’s evil plans!  Throw into the mix Santa and the Fairy Snow Queen, an insane short featuring a pixie named Snoopy, a horrific life size Jack in the Box, and a lion who is oh so proud of his candy eating ability, and you’ve got one of our funniest live shows to date. Please join Mike, Kevin, and Bill for RiffTrax Live: Santa Claus Conquers the Martians!",
      popularity: 0.6,
      poster_path: "/mM5J2CK8zAYCsQVQfOq7L5zICuu.jpg",
      release_date: "2013-12-05",
      title: "Rifftrax Live: Santa Claus Conquers the Martians",
      video: false,
      vote_average: 9.0,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/vJSnTtmGuQZHHfuuJcLlgyQF0LV.jpg",
      genre_ids: [],
      id: 524715,
      original_language: "ru",
      original_title: "Марсианские хроники нас нас нас",
      overview:
        "She is 25 years old, lives with her father and does advertising for an online casino in her video blog. The father works as cashier in a grocery shop and irons the daughter’s socks. But half an hour ago he decided that it is time to stop that.",
      popularity: 0.6,
      poster_path: "/5KsJfehGgya2WN9JY4yFRp3s7MX.jpg",
      release_date: "2018-06-07",
      title: "The Martian Chronicles of Us Us Us",
      video: false,
      vote_average: 10.0,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 612819,
      original_language: "en",
      original_title: "Harry Price \u0026 the Martian Lighthouse",
      overview:
        "The story of how famed psychical researcher Harry Price became involved in a real-life plan to build a lighthouse that could be used to direct a beam at Mars, contacting the aliens who supposedly lived there.",
      popularity: 0.6,
      poster_path: null,
      release_date: "2017-02-06",
      title: "Harry Price \u0026 the Martian Lighthouse",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 1120109,
      original_language: "en",
      original_title: "The Martian Word for World is Mother",
      overview:
        "The film mixes sci-fi with a critical approach to current proposals to colonize Mars. Presenting three possible Martian worlds, it was produced using the GPT-3 language processing model and is inspired by space ecology, interplanetary law, non-human sign systems and data science",
      popularity: 0.6,
      poster_path: null,
      release_date: "2022-10-05",
      title: "The Martian Word for World is Mother",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 960534,
      original_language: "en",
      original_title: "Hollywood in the Atomic Age - Monsters! Martians! Mad Scientists!",
      overview:
        "The only comprehensive story of Hollywood's horror and sci-fi films of the 1950s, as told by the people who made them; including rare and revealing interview and favorite fan clips.",
      popularity: 0.672,
      poster_path: "/rI29gXeCenu0nW8R3mPKXqCkyvW.jpg",
      release_date: "",
      title: "Hollywood in the Atomic Age - Monsters! Martians! Mad Scientists!",
      video: false,
      vote_average: 6.0,
      vote_count: 1,
    },
  ],
  total_pages: 2,
  total_results: 31,
};

export const sunshineMock = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/5AIAnucJKZ3sHpm7r1ykFVIoUHK.jpg",
      genre_ids: [18, 878, 53],
      id: 1272,
      original_language: "en",
      original_title: "Sunshine",
      overview:
        "Fifty years into the future, the sun is dying, and Earth is threatened by arctic temperatures. A team of astronauts is sent to revive the Sun — but the mission fails. Seven years later, a new team is sent to finish the mission as mankind’s last hope.",
      popularity: 20.105,
      poster_path: "/h2wM8RkmQiCDANgQnUjeXWNf1T7.jpg",
      release_date: "2007-04-05",
      title: "Sunshine",
      video: false,
      vote_average: 6.949,
      vote_count: 3331,
    },
    {
      adult: false,
      backdrop_path: "/6yluUpGJavNDS5ASgPCANmRKGE3.jpg",
      genre_ids: [18, 36],
      id: 17771,
      original_language: "en",
      original_title: "Sunshine",
      overview:
        "The story of a Jewish family living in Hungary—through three generations—rising from humble beginnings to positions of wealth and power in the crumbling Austro-Hungarian Empire. The patriarch becomes a prominent judge but is torn when his government sanctions anti-Jewish persecutions. His son converts to Christianity to advance his career as a champion fencer and Olympic hero, but is caught up in the Holocaust. Finally, the grandson, after surviving war, revolution, loss and betrayal, realizes that his ultimate allegiance must be to himself and his heritage.",
      popularity: 9.418,
      poster_path: "/qcHDFrjClW35u0dSuLjsQEi8gDk.jpg",
      release_date: "1999-09-13",
      title: "Sunshine",
      video: false,
      vote_average: 6.555,
      vote_count: 119,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18, 10770],
      id: 327160,
      original_language: "en",
      original_title: "Sunshine",
      overview:
        "A young woman living in the woods with her husband, a struggling musician, and her young daughter, discovers she has terminal cancer. She begins to tape-record a journal of the time she has left so her daughter will know something of her when she grows up.",
      popularity: 2.984,
      poster_path: "/1nhPgUviVBPsm4QDvFgwIo7VPOK.jpg",
      release_date: "1973-11-08",
      title: "Sunshine",
      video: false,
      vote_average: 7.3,
      vote_count: 11,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 362966,
      original_language: "en",
      original_title: "Sunshine",
      overview:
        "A geeky young man prepares for his upcoming driving test by driving his father’s taxi around in the neighbourhood nightly.",
      popularity: 0.6,
      poster_path: null,
      release_date: "2013-12-13",
      title: "Sunshine",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 406195,
      original_language: "de",
      original_title: "Sunshine",
      overview:
        "A weekend full of work is awaiting Vera. But when her ex-husband drops their sick daughter at hers, she can't keep any deadlines anymore. A close-to-life comedy/tragedy about a small family with a lot of humour.",
      popularity: 1.09,
      poster_path: null,
      release_date: "",
      title: "Sunshine",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 723554,
      original_language: "en",
      original_title: "Sunshine",
      overview:
        "Ethan refuses to accept the passing of his Mom; his Dad tries to help him cope with the loss, while also trying to get through it himself.",
      popularity: 0.6,
      poster_path: null,
      release_date: "2018-12-22",
      title: "Sunshine",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 1012683,
      original_language: "fr",
      original_title: "Sunshine",
      overview: "",
      popularity: 0.6,
      poster_path: null,
      release_date: "",
      title: "Sunshine",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 251900,
      original_language: "en",
      original_title: "Sunshine",
      overview:
        'An American advertising producer in Shanghai tries to sell fast food to the Chinese. An endearing portrait of a modern day "Mad Man."',
      popularity: 1.093,
      poster_path: "/dkwsbg4UkB8h2X3j9HJImYHAjiz.jpg",
      release_date: "2011-06-23",
      title: "Sunshine",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 772333,
      original_language: "en",
      original_title: "Sunshine",
      overview: "A 1916 short starring Jack Cooper, Hank Mann \u0026 Bobby Dunn.",
      popularity: 0.6,
      poster_path: null,
      release_date: "1916-05-06",
      title: "Sunshine",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 1099762,
      original_language: "it",
      original_title: "Sunshine",
      overview:
        "Flavio hit the jackpot: he towed Susan, a beautiful American girl. A solar flare did the rest, forcing them to live together. One day, they hear on the radio that the storm is over and it is possible to go outside again. Then, Flavio becomes... Susan's translator. He convinces her that chaos is still reigning outside, just to spend more time with her in his house, isolated. But their forced cohabitation will have a completely unexpected outcome.",
      popularity: 0.6,
      poster_path: "/f2D5rnFW18uDXAAMksHMtj0sZ0s.jpg",
      release_date: "2020-11-16",
      title: "Sunshine",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/oBHACSlfRBTysmzcSWF9KEDbHvT.jpg",
      genre_ids: [18],
      id: 2015,
      original_language: "ko",
      original_title: "밀양",
      overview:
        "Shin-ae moves to her recently late husband’s hometown. Despite her efforts to settle in this unfamiliar and too-normal place, she finds that she can’t fit in. After a sudden tragedy, Shin-ae turns to Christianity to relieve her pain, but when even this is not permitted, she wages a war against God.",
      popularity: 8.696,
      poster_path: "/vee1jyUrqUEmi5ZStWI1JJzLQJH.jpg",
      release_date: "2007-05-17",
      title: "Secret Sunshine",
      video: false,
      vote_average: 7.125,
      vote_count: 176,
    },
    {
      adult: false,
      backdrop_path: "/8AE7M2lMsyvowfT36porzGtmOtI.jpg",
      genre_ids: [878, 18, 10749],
      id: 38,
      original_language: "en",
      original_title: "Eternal Sunshine of the Spotless Mind",
      overview:
        "Joel Barish, heartbroken that his girlfriend underwent a procedure to erase him from her memory, decides to do the same. However, as he watches his memories of her fade away, he realises that he still loves her, and may be too late to correct his mistake.",
      popularity: 54.115,
      poster_path: "/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
      release_date: "2004-03-19",
      title: "Eternal Sunshine of the Spotless Mind",
      video: false,
      vote_average: 8.1,
      vote_count: 13527,
    },
    {
      adult: false,
      backdrop_path: "/4YzGG8IPduUQRVnQ0vN5laHA1rH.jpg",
      genre_ids: [35, 18],
      id: 773,
      original_language: "en",
      original_title: "Little Miss Sunshine",
      overview:
        "A family loaded with quirky, colorful characters piles into an old van and road trips to California for little Olive to compete in a beauty pageant.",
      popularity: 20.146,
      poster_path: "/tFnTds88mCuLcLPBseK1kF2E3qv.jpg",
      release_date: "2006-07-26",
      title: "Little Miss Sunshine",
      video: false,
      vote_average: 7.676,
      vote_count: 6414,
    },
    {
      adult: false,
      backdrop_path: "/muSZq30edGloLy7k8GaTFDlXVfT.jpg",
      genre_ids: [35],
      id: 74040,
      original_language: "de",
      original_title: "Sunshine Reggae auf Ibiza",
      overview:
        "Karl is a simple farmer who takes a plane to Ibiza to finally meet his idol, pop-singer Linda Lou. Karl has long ago fallen in love with his idol and has written her numerous love letters, But a farmer like Karl is not the kind of man she could be interested in. At the same time however, a famous millionaire, who happens to look just like Karl, is staying on the island",
      popularity: 3.297,
      poster_path: "/7HRef6vCJ1FSXazbq0JcbcG1Cvk.jpg",
      release_date: "1983-11-11",
      title: "Sunshine Reggae in Ibiza",
      video: false,
      vote_average: 3.5,
      vote_count: 14,
    },
    {
      adult: false,
      backdrop_path: "/tcTmBjSBMUEqJrKOg3k1lpiGhXP.jpg",
      genre_ids: [10402, 16, 35],
      id: 529589,
      original_language: "ja",
      original_title: "ラブライブ! サンシャイン!! The School Idol Movie Over The Rainbow",
      overview:
        "After the idol group Aqours has won the final Love Live! contest, its remaining members prepare to enroll at a new school only to run into some unexpected trouble while the former members go missing on the way to their graduation trip. Separated, the girls begin to realize the value of their friendships as they attempt to find a solution to their various crises.",
      popularity: 3.156,
      poster_path: "/6qqVW9a2BMR3kXEnqwMKr2rvIdq.jpg",
      release_date: "2019-01-04",
      title: "Love Live! Sunshine!! The School Idol Movie Over the Rainbow",
      video: false,
      vote_average: 6.2,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: "/pJYGDhHrZ9pN6cdqdBlnaZ6oVXA.jpg",
      genre_ids: [35, 18, 10749],
      id: 431017,
      original_language: "fr",
      original_title: "Un beau soleil intérieur",
      overview:
        "Isabelle, Parisian artist, divorced mother, is looking for love, true love, at last.",
      popularity: 6.803,
      poster_path: "/7HSbTWvHfaywSpkETtlZqqcnItT.jpg",
      release_date: "2017-09-27",
      title: "Let the Sunshine In",
      video: false,
      vote_average: 5.275,
      vote_count: 178,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [10749, 35, 18],
      id: 1100553,
      original_language: "th",
      original_title: "Sunflower\u0026Mr.Sunshine",
      overview:
        "A Minerva Fictionist who received an order to write a romantic teen fiction created ‘Hiwari’ the main character of the story that wants to approach ‘Hinode’a popular boy with a cold-hearted personality.",
      popularity: 1.223,
      poster_path: "/2xYrFZ3Pn8nCE9CkmIBSegEHjVB.jpg",
      release_date: "2023-03-08",
      title: "Sunflower\u0026Mr.Sunshine",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/iEXY8jtSD7Qa5UrA5t5xf3TfcTv.jpg",
      genre_ids: [10749, 18],
      id: 112283,
      original_language: "ko",
      original_title: "너는 내 운명",
      overview:
        "An old bachelor Seok-joong, who has no experience in dating, falls in love at first sight with a prostitute named Eun-ha. At first Eun-ha shows no interest in Seok-joong, but gradually she begins to be flattered by his devotion and eventually falls in love with him. They marry. However, one day, Eun-ha finds out that she is infected with HIV and decides to leave Seok-joong...",
      popularity: 2.698,
      poster_path: "/iAFj8oCQmTfBbQzDe2ptLzWUzD1.jpg",
      release_date: "2005-09-23",
      title: "You Are My Sunshine",
      video: false,
      vote_average: 6.717,
      vote_count: 23,
    },
    {
      adult: false,
      backdrop_path: "/4G3ahCY6Xwd7s0iG5ywSGHc6c7L.jpg",
      genre_ids: [10751, 16, 35],
      id: 15838,
      original_language: "da",
      original_title: "Disco ormene",
      overview:
        "It's not easy to be Barry. An earthworm gets no respect. He lives at the bottom of the food chain. But one day, an old disco record turns his life upside down. Suddenly he sees before him his own destiny, the star of the world's greatest disco band: Sunshine Barry \u0026amp; The Disco Worms! Okay, he's got no arms, no rhythm and no band. But as Barry says: \"We'll do it anyway!\"",
      popularity: 6.001,
      poster_path: "/eW4z9K2w7cZripBDQzdf2EAg07R.jpg",
      release_date: "2008-09-07",
      title: "Sunshine Barry \u0026 the Disco Worms",
      video: false,
      vote_average: 5.638,
      vote_count: 40,
    },
    {
      adult: false,
      backdrop_path: "/jFu0OfPvYIAHqoASuInrd0WKXkZ.jpg",
      genre_ids: [16, 12, 14, 10749, 10751],
      id: 273450,
      original_language: "ja",
      original_title: "陽なたのアオシグレ",
      overview:
        "Schoolboy Hinata has a big crush on his classmate Shigure, but is too shy to tell her. On the day Shigure is leaving, Hinata flies off on the wings of a bird chasing after her to tell how he feels!",
      popularity: 3.912,
      poster_path: "/hE41HOF9jGCNUyceyaUNDNNS52K.jpg",
      release_date: "2013-10-13",
      title: "Rain in the Sunshine",
      video: false,
      vote_average: 7.2,
      vote_count: 13,
    },
  ],
  total_pages: 13,
  total_results: 246,
};

export const allMoviesMock = {
  Sunshine: sunshineMock,
  "The Martian": martianMock,
  Interstellar: interstellarMock,
};
